name: Deploy Minified Toolkits to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build and minify site
        run: |
          set -euo pipefail
          
          # Create clean dist directory
          rm -rf dist && mkdir -p dist
          
          # Copy and minify portal root files
          npx --yes html-minifier-terser@7.2.0 \
            --collapse-whitespace --remove-comments --minify-css --minify-js \
            -o dist/index.html index.html
          
          npx --yes terser@5.21.0 app.js -c -m -o dist/app.js
          npx --yes terser@5.21.0 sw.js -c -m -o dist/sw.js
          
          # Copy manifest and assets (no minification needed)
          cp manifest.json dist/manifest.json
          [ -f favicon.ico ] && cp favicon.ico dist/favicon.ico || true
          [ -d assets ] && cp -r assets dist/assets || true
          
          # Process toolkit-a
          mkdir -p dist/toolkit-a/js
          npx --yes html-minifier-terser@7.2.0 \
            --collapse-whitespace --remove-comments --minify-css --minify-js \
            -o dist/toolkit-a/index.html toolkit-a/index.html
          npx --yes terser@5.21.0 toolkit-a/app.js -c -m -o dist/toolkit-a/app.js
          npx --yes csso-cli@5.0.5 toolkit-a/style.css --output dist/toolkit-a/style.css
          
          # Minify toolkit-a JS files
          for jsfile in toolkit-a/js/*.js; do
            [ -f "$jsfile" ] && npx --yes terser@5.21.0 "$jsfile" -c -m -o "dist/${jsfile}"
          done
          
          # Process toolkit-b
          mkdir -p dist/toolkit-b/js
          npx --yes html-minifier-terser@7.2.0 \
            --collapse-whitespace --remove-comments --minify-css --minify-js \
            -o dist/toolkit-b/index.html toolkit-b/index.html
          npx --yes terser@5.21.0 toolkit-b/app.js -c -m -o dist/toolkit-b/app.js
          npx --yes csso-cli@5.0.5 toolkit-b/style.css --output dist/toolkit-b/style.css
          
          # Minify toolkit-b JS files
          for jsfile in toolkit-b/js/*.js; do
            [ -f "$jsfile" ] && npx --yes terser@5.21.0 "$jsfile" -c -m -o "dist/${jsfile}"
          done
          
          # Add GitHub Pages configuration
          echo "          echo "<!doctype html><title>Not found</title><h1>Not found</h1><p>Return to <a href='.'>home</a>." > dist/404.html
          touch dist/.nojekyll" > dist/404.html
          touch dist/.nojekyll
          
          # Create robots.txt to prevent source file indexing
          cat > dist/robots.txt << 'ROBOTS_EOF'
          User-agent: *
          Allow: /
          
          # Only allow access to minified production files
          Disallow: /src/
          Disallow: /*.ts
          Disallow: /*.scss
          ROBOTS_EOF

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
